version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: carshop-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:-Your@StrongP4ssw0rd}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      # TCP check without requiring sqlcmd in the image
      test: ["CMD-SHELL", "bash -lc 'echo > /dev/tcp/127.0.0.1/1433'"]
      interval: 5s
      timeout: 2s
      retries: 30
      start_period: 10s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carshop-web
    env_file:
      - .env
    environment:
      # Defaults if not in .env
      - DB_ENGINE=${DB_ENGINE:-mssql}
      - DB_HOST=${DB_HOST:-sqlserver}
      - DB_PORT=${DB_PORT:-1433}
      - DB_NAME=${DB_NAME:-carshop}
      - DB_USER=${DB_USER:-sa}
      - DB_PASSWORD=${DB_PASSWORD:-Your@StrongP4ssw0rd}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-1}
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["/usr/local/bin/entrypoint.sh"]

volumes:
  mssql_data:
