version: '3.8'

services:
  web:
    build: .
    expose:
      - "8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-change-this-in-production-make-it-very-long-and-random-key-for-security
      - ALLOWED_HOSTS=192.3.154.52,localhost
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/var/www/staticfiles
      - ./media:/var/www/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
