version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: carshop-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:-YourStrong!Passw0rd}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/1433' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  web:
    build: .
    container_name: carshop-web
    ports:
      - "8000:8000"
    environment:
      # Database
      - DB_ENGINE=mssql
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_NAME=carshop
      - DB_USER=sa
      - DB_PASSWORD=${SA_PASSWORD:-YourStrong!Passw0rd}
      # Django
      - DEBUG=1
    volumes:
      - .:/app
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  mssql_data:
