version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DB_ENGINE=sqlite
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
