version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-for-testing-only
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    restart: unless-stopped
