version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
